apiVersion: v1
kind: Pod
metadata:
  name: todo-app-pod
  labels:
    app: todo-app
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}

  containers:
    - name: postgres
      image: postgres:16
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "pass"
        - name: POSTGRES_DB
          value: "tododb"

    - name: api
      image: todo-api:1.0
      imagePullPolicy: Never
      ports:
        - containerPort: 4444
      env:
        - name: DATABASE_URL
          value: "postgresql://user:pass@localhost:5432/tododb"
      command: ["/bin/sh", "-c"]
      args:
        - sleep 15 && ./run-api.sh

    - name: pgadmin
      image: dpage/pgadmin4
      ports:
        - containerPort: 80
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@admin.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin"

    - name: log-writer
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - while true; do echo "$(date) - log from log-writer container" >> /shared/logs/app.log; sleep 5; done
      volumeMounts:
        - name: shared-logs
          mountPath: /shared/logs

    - name: log-reader
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - touch /shared/logs/app.log && tail -f /shared/logs/app.log
      volumeMounts:
        - name: shared-logs
          mountPath: /shared/logs

---
apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
    - name: api
      protocol: TCP
      port: 4444
      targetPort: 4444
      nodePort: 30444
    - name: pgadmin
      protocol: TCP
      port: 5050
      targetPort: 80
      nodePort: 30505