apiVersion: v1
kind: Pod
metadata:
  name: hostpath-writer-pod
  labels:
    app: hostpath-writer
spec:
  containers:
    - name: writer
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - while true; do echo "$(date) - log from hostpath-writer-pod" >> /node-logs/app.log; sleep 5; done
      volumeMounts:
        - name: node-shared-logs
          mountPath: /node-logs
  volumes:
    - name: node-shared-logs
      hostPath:
        path: /data/shared-logs
        type: DirectoryOrCreate